// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgCvkt_AU5AvlVSQzcoHaqKEI6YnsQ8O4',
    appId: '1:353268434156:web:bb45c8a7bfcceae60751c9',
    messagingSenderId: '353268434156',
    projectId: 'nutrition-app-c44dd',
    authDomain: 'nutrition-app-c44dd.firebaseapp.com',
    storageBucket: 'nutrition-app-c44dd.firebasestorage.app',
    measurementId: 'G-VFMX66ZV5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKg70z3tPbbwH_NTrxuO7Xg1UZWETau8',
    appId: '1:353268434156:android:bdb3e5f15e3a10a20751c9',
    messagingSenderId: '353268434156',
    projectId: 'nutrition-app-c44dd',
    storageBucket: 'nutrition-app-c44dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmmDWncf5P_7pjhyWqxRXvR10D44yRYQ',
    appId: '1:353268434156:ios:51d65c645fb0f6c80751c9',
    messagingSenderId: '353268434156',
    projectId: 'nutrition-app-c44dd',
    storageBucket: 'nutrition-app-c44dd.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSmmDWncf5P_7pjhyWqxRXvR10D44yRYQ',
    appId: '1:353268434156:ios:51d65c645fb0f6c80751c9',
    messagingSenderId: '353268434156',
    projectId: 'nutrition-app-c44dd',
    storageBucket: 'nutrition-app-c44dd.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgCvkt_AU5AvlVSQzcoHaqKEI6YnsQ8O4',
    appId: '1:353268434156:web:e738f59b65da1c130751c9',
    messagingSenderId: '353268434156',
    projectId: 'nutrition-app-c44dd',
    authDomain: 'nutrition-app-c44dd.firebaseapp.com',
    storageBucket: 'nutrition-app-c44dd.firebasestorage.app',
    measurementId: 'G-8QR1F94JQP',
  );
}
